name: .NET Core

on:
  push:
    branches:
      - master
      - 'features/**'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish EdgeManager\EdgeManager.csproj -r win10-x64 -c Release /p:PublishSingleFile=true -o out
    - name: Compress
      run: Compress-Archive out\EdgeManager.exe EdgeManager_${{ github.run_number }}.zip
    - uses: actions/upload-artifact@v2
      with:
        name: EdgeManager_${{ github.run_number }}.zip
        path: EdgeManager_${{ github.run_number }}.zip

